import assert from "node:assert/strict";
import { test } from "node:test";
import {
  NativeTemplateProjectionError,
  parseArtifactContract,
  projectArtifactContractToIssueForm,
  projectArtifactContractToPullRequestTemplate,
} from "./index.js";

const issueContract = {
  version: "1",
  kind: "issue",
  id: "feature",
  properties: {},
  fields: [
    { id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } },
    {
      id: "areas",
      primitive: "choice",
      presence: "optional",
      authority: { kind: "supplied" },
      constraints: { values: ["core", "cli"] },
    },
    {
      id: "checks",
      primitive: "checklist",
      presence: "optional",
      authority: { kind: "supplied" },
      constraints: { items: [{ id: "tests", label: "Tests", required: true }] },
    },
  ],
} as const;

test("projects an Issue Artifact Contract directly to a deterministic Issue Form", () => {
  const contract = parseArtifactContract(issueContract);
  const first = projectArtifactContractToIssueForm(contract);
  const second = projectArtifactContractToIssueForm(structuredClone(issueContract));

  assert.equal(first.path, ".github/ISSUE_TEMPLATE/feature.yml");
  assert.equal(first.content, second.content);
  assert.match(first.content, /type: textarea/u);
  assert.match(first.content, /multiple: true/u);
  assert.match(first.content, /required: true/u);
  assert.match(first.content, /label: Tests/u);
});

test("projects supported PR text/checklist fields without treating Markdown as Canon", () => {
  const contract = parseArtifactContract({
    version: "1",
    kind: "pull_request",
    id: "default",
    properties: {},
    fields: [
      { id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } },
      {
        id: "checks",
        primitive: "checklist",
        presence: "optional",
        authority: { kind: "supplied" },
        constraints: { items: [{ id: "tests", label: "Tests", required: false }] },
      },
    ],
  });
  const projection = projectArtifactContractToPullRequestTemplate(contract);
  assert.equal(projection.path, ".github/PULL_REQUEST_TEMPLATE.md");
  assert.match(projection.content, /^<!-- Generated by gh-inari from Artifact Contract; do not edit\. -->/u);
  assert.match(projection.content, /## summary\n\n## checks\n\n- \[ \] Tests/u);
});

test("fails closed for native capabilities that cannot preserve semantic state", () => {
  const attachment = parseArtifactContract({
    version: "1",
    kind: "issue",
    id: "attachment",
    properties: {},
    fields: [
      {
        id: "files",
        primitive: "attachment",
        presence: "required",
        authority: { kind: "supplied" },
        constraints: { minItems: 1 },
      },
    ],
  });
  assert.throws(
    () => projectArtifactContractToIssueForm(attachment),
    (error: unknown) =>
      error instanceof NativeTemplateProjectionError &&
      error.violations.some((violation) => violation.code === "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY"),
  );

  const choice = parseArtifactContract({
    version: "1",
    kind: "pull_request",
    id: "choice",
    properties: {},
    fields: [
      {
        id: "area",
        primitive: "choice",
        presence: "required",
        authority: { kind: "supplied" },
        constraints: { values: ["core"] },
      },
    ],
  });
  assert.throws(() => projectArtifactContractToPullRequestTemplate(choice), NativeTemplateProjectionError);
});
