import { stringify as stringifyYaml } from "yaml";
import {
  parseArtifactContract,
  serializeArtifactContract,
  type ArtifactContract,
  type FieldDeclaration,
} from "./artifact-contract.js";

/** Marker shared by generated native GitHub template projections. */
export const ARTIFACT_CONTRACT_TEMPLATE_NOTICE = "Generated by gh-inari from Artifact Contract; do not edit." as const;

export type NativeTemplateProjectionKind = "issue_form" | "pull_request_template";

export interface NativeTemplateProjection {
  readonly kind: NativeTemplateProjectionKind;
  readonly path: string;
  /** Parsed native representation, before serialization. */
  readonly document: Readonly<Record<string, unknown>>;
  /** Deterministic native source suitable for a committed projection. */
  readonly content: string;
}

export type NativeIssueFormProjection = NativeTemplateProjection & {
  readonly kind: "issue_form";
  readonly document: Readonly<{
    readonly name: string;
    readonly description: string;
    readonly body: readonly Record<string, unknown>[];
  }>;
};

export type NativePullRequestTemplateProjection = NativeTemplateProjection & {
  readonly kind: "pull_request_template";
  readonly document: Readonly<Record<string, unknown>>;
};

export type NativeTemplateProjectionResult = NativeIssueFormProjection | NativePullRequestTemplateProjection;

export type NativeTemplateProjectionViolationCode =
  | "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT"
  | "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY"
  | "NATIVE_TEMPLATE_PROJECTION_EMPTY";

export interface NativeTemplateProjectionViolation {
  readonly code: NativeTemplateProjectionViolationCode;
  readonly path: string;
  readonly message: string;
}

/** Bounded failure raised when a Canon value cannot be projected safely. */
export class NativeTemplateProjectionError extends Error {
  readonly violations: readonly NativeTemplateProjectionViolation[];

  constructor(violations: readonly NativeTemplateProjectionViolation[]) {
    if (violations.length === 0) throw new Error("Native template projection errors require a violation.");
    super(violations.map((violation) => `${violation.path}: ${violation.message}`).join("\n"));
    this.name = "NativeTemplateProjectionError";
    this.violations = Object.freeze([...violations]);
  }
}

export interface ArtifactContractNativeTemplateProjectionOptions {
  /** Repository-relative generated path. Defaults to the conventional path for the contract identity. */
  readonly path?: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function contractFromInput(input: unknown): ArtifactContract {
  try {
    // A normalized ArtifactContract carries Core-computed derivation metadata.
    // Re-serialize it before parsing so malformed caller objects cannot bypass
    // the repository Canon parser, while raw Canon JSON remains accepted.
    if (isRecord(input) && Array.isArray(input.derivations)) {
      return parseArtifactContract(
        JSON.parse(serializeArtifactContract(input as unknown as ArtifactContract)) as unknown,
      );
    }
    return parseArtifactContract(input);
  } catch (error: unknown) {
    if (error instanceof NativeTemplateProjectionError) throw error;
    const message = error instanceof Error ? error.message : "Artifact Contract is invalid.";
    throw new NativeTemplateProjectionError([
      { code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT", path: "$", message },
    ]);
  }
}

function generatedPath(contract: Pick<ArtifactContract, "kind" | "id">, path: string | undefined): string {
  if (path !== undefined) return path;
  if (contract.kind === "issue") return `.github/ISSUE_TEMPLATE/${contract.id}.yml`;
  return contract.id === "default" || contract.id === "pull-request"
    ? ".github/PULL_REQUEST_TEMPLATE.md"
    : `.github/PULL_REQUEST_TEMPLATE/${contract.id}.md`;
}

type ActiveField = Extract<FieldDeclaration, { readonly presence: "required" | "optional" }>;

function activeField(field: FieldDeclaration): field is ActiveField {
  return field.presence !== "unused";
}

function requiredField(field: ActiveField): boolean {
  return field.presence === "required";
}

function suppliedField(field: FieldDeclaration): field is ActiveField {
  return field.presence !== "unused" && field.authority.kind === "supplied";
}

function addUnsupported(violations: NativeTemplateProjectionViolation[], path: string, message: string): void {
  violations.push({ code: "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY", path, message });
}

function issueFieldElement(field: ActiveField): Record<string, unknown> {
  if (field.primitive === "text") {
    return {
      type: "textarea",
      id: field.id,
      attributes: { label: field.id },
      ...(requiredField(field) ? { validations: { required: true } } : {}),
    };
  }
  if (field.primitive === "choice") {
    const values = field.constraints?.values ?? [];
    return {
      type: "dropdown",
      id: field.id,
      attributes: { label: field.id, options: values, multiple: true },
      ...(requiredField(field) ? { validations: { required: true } } : {}),
    };
  }
  const items = field.constraints?.items ?? [];
  return {
    type: "checkboxes",
    id: field.id,
    attributes: {
      label: field.id,
      options: items.map((item) => ({ label: item.label, ...(item.required ? { required: true } : {}) })),
    },
    ...(requiredField(field) ? { validations: { required: true } } : {}),
  };
}

function validateIssueFields(contract: ArtifactContract): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  for (const [index, field] of (contract.fields ?? []).entries()) {
    if (field.primitive === "attachment")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Attachment fields have no supported native Issue Form projection.",
      );
    if (field.primitive === "choice" && activeField(field)) {
      const minItems = field.constraints?.minItems ?? 0;
      const maxItems = field.constraints?.maxItems;
      const values = field.constraints?.values ?? [];
      if (values.some((value) => value !== value.trim() || value.includes(",")))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.values`,
          "Native Issue Form multi-select options cannot contain commas or surrounding whitespace.",
        );
      if (maxItems !== undefined)
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.maxItems`,
          "Native Issue Form multi-select cannot enforce a maximum selection count.",
        );
      if (minItems > 1 || (minItems > 0 && !requiredField(field)))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.minItems`,
          "Native Issue Form can enforce only the required/non-required selection boundary.",
        );
    }
    if (field.primitive === "checklist" && activeField(field)) {
      const labels = (field.constraints?.items ?? []).map((item) => item.label);
      if (new Set(labels).size !== labels.length || labels.some((label) => label !== label.trim()))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native Issue Form checklist labels must be unique and trimmed.",
        );
    }
  }
  return violations;
}

function validatePullRequestFields(contract: ArtifactContract): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  for (const [index, field] of (contract.fields ?? []).entries()) {
    if (field.primitive === "choice")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Choice fields have no native pull-request-template field representation.",
      );
    if (field.primitive === "attachment")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Attachment fields have no native pull-request-template field representation.",
      );
    if (field.primitive === "checklist" && activeField(field)) {
      const items = field.constraints?.items ?? [];
      if (items.some((item) => item.required))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native pull-request Markdown cannot encode required checklist items.",
        );
      const labels = items.map((item) => item.label);
      if (new Set(labels).size !== labels.length || labels.some((label) => label !== label.trim()))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native pull-request Markdown checklist labels must be unique and trimmed.",
        );
    }
  }
  return violations;
}

function issueDocument(contract: ArtifactContract): Readonly<Record<string, unknown>> {
  const fields = (contract.fields ?? []).filter(suppliedField);
  return {
    name: contract.id,
    description: `Artifact Contract ${contract.id}`,
    body: fields.map((field) => issueFieldElement(field)),
  };
}

function renderIssueDocument(document: Readonly<Record<string, unknown>>): string {
  return `# ${ARTIFACT_CONTRACT_TEMPLATE_NOTICE}\n${stringifyYaml(document, { lineWidth: 0 })}`;
}

function markdownField(field: ActiveField): string {
  const heading = `## ${field.id}`;
  if (field.primitive === "text") return heading;
  const items = (field.constraints?.items ?? []).map((item) => `- [ ] ${item.label}`).join("\n");
  return `${heading}\n\n${items}`;
}

function renderPullRequestDocument(contract: ArtifactContract): string {
  const fields = (contract.fields ?? []).filter(suppliedField);
  return `${fields.map(markdownField).join("\n\n")}\n`;
}

/** Project a v2 Issue Artifact Contract into a native Issue Form. */
export function projectArtifactContractToIssueForm(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativeIssueFormProjection {
  const contract = contractFromInput(input);
  if (contract.kind !== "issue")
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Issue Form projection requires an issue contract.",
      },
    ]);
  const violations = [...validateIssueFields(contract)];
  const supplied = (contract.fields ?? []).some(suppliedField);
  if (!supplied)
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.fields",
      message: "Issue Form projection requires at least one supplied body field.",
    });
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  const document = issueDocument(contract);
  return {
    kind: "issue_form",
    path: generatedPath(contract, options.path),
    document: document as NativeIssueFormProjection["document"],
    content: renderIssueDocument(document),
  };
}

/** Project a v2 Pull Request Artifact Contract into a native Markdown template. */
export function projectArtifactContractToPullRequestTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativePullRequestTemplateProjection {
  const contract = contractFromInput(input);
  if (contract.kind !== "pull_request")
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Pull request template projection requires a pull_request contract.",
      },
    ]);
  const violations = [...validatePullRequestFields(contract)];
  const supplied = (contract.fields ?? []).some(suppliedField);
  if (!supplied)
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.fields",
      message: "Pull request template projection requires at least one supplied body field.",
    });
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  return {
    kind: "pull_request_template",
    path: generatedPath(contract, options.path),
    document: {},
    content: `<!-- ${ARTIFACT_CONTRACT_TEMPLATE_NOTICE} -->\n\n${renderPullRequestDocument(contract)}`,
  };
}

/** Project an Artifact Contract to its kind-specific native GitHub template. */
export function projectArtifactContractToNativeTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativeTemplateProjectionResult {
  const contract = contractFromInput(input);
  return contract.kind === "issue"
    ? projectArtifactContractToIssueForm(contract, options)
    : contract.kind === "pull_request"
      ? projectArtifactContractToPullRequestTemplate(contract, options)
      : (() => {
          throw new NativeTemplateProjectionError([
            {
              code: "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY",
              path: "$.kind",
              message: "Branch Artifact Contracts do not have a native Issue Form or pull-request-template projection.",
            },
          ]);
        })();
}

export function renderArtifactContractIssueForm(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToIssueForm(input, options).content;
}

export function renderArtifactContractPullRequestTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToPullRequestTemplate(input, options).content;
}

export function renderArtifactContractNativeTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToNativeTemplate(input, options).content;
}

// Naming aliases follow the existing semantic artifact projection surface and
// keep callers from having to encode the target's historical file format.
export const projectIssueArtifactContract = projectArtifactContractToIssueForm;
export const projectPullRequestArtifactContract = projectArtifactContractToPullRequestTemplate;
export const projectArtifactContractToNative = projectArtifactContractToNativeTemplate;
export const renderArtifactContractToIssueForm = renderArtifactContractIssueForm;
export const renderArtifactContractToPullRequestTemplate = renderArtifactContractPullRequestTemplate;

/** Stable path helper shared by local template sync and callers previewing output. */
export function artifactContractNativeTemplatePath(contract: Pick<ArtifactContract, "kind" | "id">): string {
  return generatedPath(contract, undefined);
}
