import { stringify as stringifyYaml } from "yaml";
import {
  parseArtifactContract,
  serializeArtifactContract,
  type ArtifactContract,
  type FieldDeclaration,
  type PropertyValueDeclaration,
  type SchemaNativeArtifactContract,
} from "./artifact-contract.js";
import { buildSchemaNativeInputSchema } from "./effective-artifact-contract.js";
import { compileJsonSchema } from "./json-schema-runtime.js";

/** Marker shared by generated native GitHub template projections. */
export const ARTIFACT_CONTRACT_TEMPLATE_NOTICE = "Generated by gh-inari from Artifact Contract; do not edit." as const;

export type NativeTemplateProjectionKind = "issue_form" | "pull_request_template";

export interface NativeTemplateProjection {
  readonly kind: NativeTemplateProjectionKind;
  readonly path: string;
  /** Parsed native representation, before serialization. */
  readonly document: Readonly<Record<string, unknown>>;
  /** Deterministic native source suitable for a committed projection. */
  readonly content: string;
}

export type NativeIssueFormProjection = NativeTemplateProjection & {
  readonly kind: "issue_form";
  readonly document: Readonly<{
    readonly name: string;
    readonly description: string;
    /** Fixed-value governed properties the native Issue Form top level can represent. */
    readonly title?: string;
    readonly labels?: readonly string[];
    readonly assignees?: readonly string[];
    readonly body: readonly Record<string, unknown>[];
  }>;
};

export type NativePullRequestTemplateProjection = NativeTemplateProjection & {
  readonly kind: "pull_request_template";
  readonly document: Readonly<Record<string, unknown>>;
};

export type NativeTemplateProjectionResult = NativeIssueFormProjection | NativePullRequestTemplateProjection;

export type NativeTemplateProjectionViolationCode =
  | "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT"
  | "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY"
  | "NATIVE_TEMPLATE_PROJECTION_EMPTY";

export interface NativeTemplateProjectionViolation {
  readonly code: NativeTemplateProjectionViolationCode;
  readonly path: string;
  readonly message: string;
}

/** Bounded failure raised when a Canon value cannot be projected safely. */
export class NativeTemplateProjectionError extends Error {
  readonly violations: readonly NativeTemplateProjectionViolation[];

  constructor(violations: readonly NativeTemplateProjectionViolation[]) {
    if (violations.length === 0) throw new Error("Native template projection errors require a violation.");
    super(violations.map((violation) => `${violation.path}: ${violation.message}`).join("\n"));
    this.name = "NativeTemplateProjectionError";
    this.violations = Object.freeze([...violations]);
  }
}

export interface ArtifactContractNativeTemplateProjectionOptions {
  /** Repository-relative generated path. Defaults to the conventional path for the contract identity. */
  readonly path?: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function contractFromInput(input: unknown): ArtifactContract {
  try {
    // A normalized ArtifactContract carries Core-computed derivation metadata.
    // Re-serialize it before parsing so malformed caller objects cannot bypass
    // the repository Canon parser, while raw Canon JSON remains accepted.
    if (isRecord(input) && Array.isArray(input.derivations)) {
      return parseArtifactContract(
        JSON.parse(serializeArtifactContract(input as unknown as ArtifactContract)) as unknown,
      );
    }
    return parseArtifactContract(input);
  } catch (error: unknown) {
    if (error instanceof NativeTemplateProjectionError) throw error;
    const message = error instanceof Error ? error.message : "Artifact Contract is invalid.";
    throw new NativeTemplateProjectionError([
      { code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT", path: "$", message },
    ]);
  }
}

function generatedPath(contract: Pick<ArtifactContract, "kind" | "id">, path: string | undefined): string {
  if (path !== undefined) return path;
  if (contract.kind === "issue") return `.github/ISSUE_TEMPLATE/${contract.id}.yml`;
  return contract.id === "default" || contract.id === "pull-request"
    ? ".github/PULL_REQUEST_TEMPLATE.md"
    : `.github/PULL_REQUEST_TEMPLATE/${contract.id}.md`;
}

type ActiveField = Extract<FieldDeclaration, { readonly presence: "required" | "optional" }>;

function activeField(field: FieldDeclaration): field is ActiveField {
  return field.presence !== "unused";
}

function requiredField(field: ActiveField): boolean {
  return field.presence === "required";
}

function suppliedField(field: FieldDeclaration): field is ActiveField {
  return field.presence !== "unused" && field.authority.kind === "supplied";
}

function addUnsupported(violations: NativeTemplateProjectionViolation[], path: string, message: string): void {
  violations.push({ code: "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY", path, message });
}

type ActiveProperty = Extract<PropertyValueDeclaration, { readonly presence: "required" | "optional" }>;

function activeProperty(declaration: PropertyValueDeclaration): declaration is ActiveProperty {
  return declaration.presence !== "unused";
}

const MAX_SCHEMA_NATIVE_PROJECTION_DIAGNOSTICS = 16;
const MAX_SCHEMA_NATIVE_MARKDOWN_DEPTH = 8;
const MAX_SCHEMA_NATIVE_MARKDOWN_NODES = 256;
const MAX_SCHEMA_NATIVE_MARKDOWN_ARRAY_ITEMS = 64;

function isSchemaNativeContract(contract: ArtifactContract): contract is SchemaNativeArtifactContract {
  return contract.version === "2";
}

function schemaProperties(contract: SchemaNativeArtifactContract): Readonly<Record<string, unknown>> {
  return contract.schema.properties as Readonly<Record<string, unknown>>;
}

function schemaBinding(contract: SchemaNativeArtifactContract, name: string) {
  return contract.bindings[`/${name.replaceAll("~", "~0").replaceAll("/", "~1")}`];
}

function schemaRequired(contract: SchemaNativeArtifactContract): ReadonlySet<string> {
  return new Set(Array.isArray(contract.schema.required) ? (contract.schema.required as readonly string[]) : []);
}

function addSchemaUnsupported(violations: NativeTemplateProjectionViolation[], path: string, message: string): void {
  if (violations.length >= MAX_SCHEMA_NATIVE_PROJECTION_DIAGNOSTICS) return;
  addUnsupported(violations, path.length <= 256 ? path : "$", message);
}

function stringSchemaEnum(schema: unknown): readonly string[] | undefined {
  if (!isRecord(schema) || !Array.isArray(schema.enum)) return undefined;
  return schema.enum.every((entry): entry is string => typeof entry === "string") ? schema.enum : [];
}

function issueFormOptionLabels(
  binding: SchemaNativeArtifactContract["bindings"][string],
  values: readonly string[],
  path: string,
  violations: NativeTemplateProjectionViolation[],
): readonly string[] | undefined {
  const options = binding.presentation?.options;
  if (options === undefined) return [...values];
  const keys = Object.keys(options);
  if (keys.length !== values.length || values.some((value) => !Object.hasOwn(options, value))) {
    addSchemaUnsupported(
      violations,
      `${path}.presentation.options`,
      "Issue Form option labels must cover the complete schema enum so each choice remains reversible.",
    );
    return undefined;
  }
  return values.map((value) => options[value] as string);
}

function validateSchemaNativeIssueForm(
  contract: SchemaNativeArtifactContract,
): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  const names = Object.keys(schemaProperties(contract)).sort((left, right) => left.localeCompare(right, "en-US"));
  if (!names.some((name) => schemaBinding(contract, name)?.authority.kind === "supplied")) {
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.bindings",
      message: "Issue Form projection requires at least one supplied property.",
    });
    return violations;
  }
  for (const name of names) {
    const binding = schemaBinding(contract, name);
    if (binding?.authority.kind !== "supplied") continue;
    const path = `$.schema.properties.${name}`;
    if (!/^[A-Za-z0-9_-]+$/u.test(name)) {
      addSchemaUnsupported(
        violations,
        path,
        "Native Issue Form field identifiers must preserve the schema property name using GitHub's bounded identifier syntax.",
      );
      continue;
    }
    const propertySchema = schemaProperties(contract)[name];
    if (!isRecord(propertySchema)) {
      addSchemaUnsupported(violations, path, "Native Issue Form supports only direct scalar string properties.");
      continue;
    }
    const type = propertySchema.type;
    const enumValues = stringSchemaEnum(propertySchema);
    const control = binding.presentation?.control;
    if (type !== "string") {
      addSchemaUnsupported(
        violations,
        path,
        "Native Issue Form supports only direct string properties; structured, numeric, and boolean values need a reversible provider control.",
      );
      continue;
    }
    if (Array.isArray(propertySchema.enum) && (enumValues === undefined || enumValues.length === 0)) {
      addSchemaUnsupported(violations, `${path}.enum`, "Native Issue Form choices must be a non-empty string enum.");
      continue;
    }
    if (enumValues !== undefined) {
      if (enumValues.length === 0 || enumValues.length > 32 || new Set(enumValues).size !== enumValues.length) {
        addSchemaUnsupported(
          violations,
          `${path}.enum`,
          "Native Issue Form choices must contain between one and 32 unique string values.",
        );
        continue;
      }
      const labels = issueFormOptionLabels(
        binding,
        enumValues,
        `$.bindings.${name.replaceAll("~", "~0").replaceAll("/", "~1")}`,
        violations,
      );
      if (labels === undefined) continue;
      if (
        labels.some(
          (label) =>
            label.length === 0 ||
            label !== label.trim() ||
            label === "_No response_" ||
            label.includes(",") ||
            /[\r\n]/u.test(label),
        ) ||
        new Set(labels).size !== labels.length
      ) {
        addSchemaUnsupported(
          violations,
          `${path}.enum`,
          "Native Issue Form choice labels must be unique, trimmed, non-empty, and free of reserved or ambiguous text.",
        );
      }
      if (control !== undefined && control !== "choice") {
        addSchemaUnsupported(
          violations,
          `$.bindings.${name.replaceAll("~", "~0").replaceAll("/", "~1")}.presentation.control`,
          `Presentation control "${control}" cannot represent a closed string choice through an Issue Form dropdown.`,
        );
      }
      if (binding.presentation?.options !== undefined && control !== "choice") {
        addSchemaUnsupported(
          violations,
          `$.bindings.${name.replaceAll("~", "~0").replaceAll("/", "~1")}.presentation.control`,
          "Issue Form option labels require the target-neutral choice presentation control.",
        );
      }
    } else {
      const minLength = typeof propertySchema.minLength === "number" ? propertySchema.minLength : 0;
      const fixed = typeof propertySchema.const === "string" ? propertySchema.const : undefined;
      if (minLength < 1 && (fixed === undefined || fixed.length === 0)) {
        addSchemaUnsupported(
          violations,
          path,
          "Native Issue Form text cannot distinguish an empty string from GitHub's no-response value.",
        );
      }
      if (binding.presentation?.options !== undefined) {
        addSchemaUnsupported(
          violations,
          `$.bindings.${name.replaceAll("~", "~0").replaceAll("/", "~1")}.presentation.options`,
          "Presentation options require a closed string enum to remain reversible.",
        );
      }
      if (control !== undefined && control !== "text" && control !== "multiline") {
        addSchemaUnsupported(
          violations,
          `$.bindings.${name.replaceAll("~", "~0").replaceAll("/", "~1")}.presentation.control`,
          `Presentation control "${control}" has no reversible native Issue Form text representation.`,
        );
      }
    }
  }
  return violations;
}

function validateSchemaNativeCallerInputProjection(
  contract: SchemaNativeArtifactContract,
  violations: NativeTemplateProjectionViolation[],
): void {
  try {
    compileJsonSchema(buildSchemaNativeInputSchema(contract));
  } catch (error: unknown) {
    addSchemaUnsupported(
      violations,
      "$.schema",
      error instanceof Error
        ? `Core cannot project the schema-native caller input equivalently: ${error.message}`
        : "Core cannot project the schema-native caller input equivalently.",
    );
  }
}

function validateSchemaNativeMarkdownNode(
  schema: unknown,
  path: string,
  depth: number,
  budget: { nodes: number },
  violations: NativeTemplateProjectionViolation[],
): void {
  budget.nodes += 1;
  if (budget.nodes > MAX_SCHEMA_NATIVE_MARKDOWN_NODES) {
    addSchemaUnsupported(violations, path, "Structured Markdown projection exceeds its bounded node count.");
    return;
  }
  if (depth > MAX_SCHEMA_NATIVE_MARKDOWN_DEPTH) {
    addSchemaUnsupported(violations, path, "Structured Markdown projection exceeds its bounded nesting depth.");
    return;
  }
  if (!isRecord(schema)) {
    addSchemaUnsupported(violations, path, "Structured Markdown projection requires an explicit schema node shape.");
    return;
  }
  if (["string", "number", "integer", "boolean", "null"].includes(String(schema.type))) return;
  if (schema.type === "array") {
    if (
      typeof schema.maxItems !== "number" ||
      schema.maxItems < 0 ||
      schema.maxItems > MAX_SCHEMA_NATIVE_MARKDOWN_ARRAY_ITEMS
    ) {
      addSchemaUnsupported(
        violations,
        `${path}.maxItems`,
        `Structured Markdown arrays require a schema maximum of at most ${MAX_SCHEMA_NATIVE_MARKDOWN_ARRAY_ITEMS} items.`,
      );
    }
    validateSchemaNativeMarkdownNode(schema.items, `${path}.items`, depth + 1, budget, violations);
    return;
  }
  if (schema.type === "object") {
    if (schema.additionalProperties !== false || !isRecord(schema.properties)) {
      addSchemaUnsupported(
        violations,
        path,
        "Structured Markdown objects require declared properties and additionalProperties: false.",
      );
      return;
    }
    if (isRecord(schema.patternProperties) && Object.keys(schema.patternProperties).length > 0) {
      addSchemaUnsupported(
        violations,
        `${path}.patternProperties`,
        "Structured Markdown cannot preserve dynamically named object properties.",
      );
      return;
    }
    const properties = Object.entries(schema.properties);
    if (properties.length > MAX_SCHEMA_NATIVE_MARKDOWN_NODES) {
      addSchemaUnsupported(violations, `${path}.properties`, "Structured Markdown object has too many properties.");
      return;
    }
    for (const [name, child] of properties) {
      validateSchemaNativeMarkdownNode(child, `${path}.properties.${name}`, depth + 1, budget, violations);
    }
    return;
  }
  addSchemaUnsupported(
    violations,
    path,
    "Structured Markdown supports only explicit scalar, bounded homogeneous array, and closed object schema nodes.",
  );
}

function validateSchemaNativePullRequestMarkdown(
  contract: SchemaNativeArtifactContract,
): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  const properties = schemaProperties(contract);
  const supplied = Object.keys(properties).filter(
    (name) => schemaBinding(contract, name)?.authority.kind === "supplied",
  );
  if (supplied.length === 0) {
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.bindings",
      message: "Pull request Markdown projection requires at least one supplied property.",
    });
    return violations;
  }
  const budget = { nodes: 0 };
  for (const name of supplied.sort((left, right) => left.localeCompare(right, "en-US"))) {
    validateSchemaNativeMarkdownNode(properties[name], `$.schema.properties.${name}`, 0, budget, violations);
  }
  return violations;
}

/** Assert the bounded Issue Form capability subset for a parsed schema-native contract. */
export function assertSchemaNativeIssueFormCapability(input: unknown): SchemaNativeArtifactContract {
  const contract = contractFromInput(input);
  if (!isSchemaNativeContract(contract) || contract.kind !== "issue") {
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Schema-native Issue Form projection requires a schema-native issue contract.",
      },
    ]);
  }
  const violations = [...validateSchemaNativeIssueForm(contract)];
  validateSchemaNativeCallerInputProjection(contract, violations);
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  return contract;
}

/** Assert the bounded structured Markdown capability subset for a parsed schema-native contract. */
export function assertSchemaNativePullRequestMarkdownCapability(input: unknown): SchemaNativeArtifactContract {
  const contract = contractFromInput(input);
  if (!isSchemaNativeContract(contract) || contract.kind !== "pull_request") {
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Schema-native Markdown projection requires a schema-native pull_request contract.",
      },
    ]);
  }
  const violations = [...validateSchemaNativePullRequestMarkdown(contract)];
  validateSchemaNativeCallerInputProjection(contract, violations);
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  return contract;
}

/** A Markdown-safe stable field identity shared by schema-native PR template and artifact adapters. */
export function schemaNativeMarkdownFieldHeading(name: string): string {
  const token = encodeURIComponent(name).replace(
    /[!'()*]/gu,
    (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`,
  );
  return `inari-field:${token}`;
}

function schemaNativeIssueDocument(contract: SchemaNativeArtifactContract): Readonly<Record<string, unknown>> {
  const properties = schemaProperties(contract);
  const required = schemaRequired(contract);
  const body: Record<string, unknown>[] = [];
  for (const name of Object.keys(properties).sort((left, right) => left.localeCompare(right, "en-US"))) {
    const binding = schemaBinding(contract, name);
    if (binding?.authority.kind !== "supplied") continue;
    const propertySchema = properties[name] as Record<string, unknown>;
    const enumValues = stringSchemaEnum(propertySchema);
    const fieldRequired = required.has(name);
    if (enumValues !== undefined) {
      const labels = issueFormOptionLabels(binding, enumValues, `$.bindings.${name}`, []);
      body.push({
        type: "dropdown",
        id: name,
        attributes: { label: name, options: labels ?? [...enumValues] },
        ...(fieldRequired ? { validations: { required: true } } : {}),
      });
      continue;
    }
    body.push({
      type: binding.presentation?.control === "text" ? "input" : "textarea",
      id: name,
      attributes: { label: name },
      ...(fieldRequired ? { validations: { required: true } } : {}),
    });
  }
  return { name: contract.id, description: `Artifact Contract ${contract.id}`, body };
}

function renderSchemaNativePullRequestDocument(contract: SchemaNativeArtifactContract): string {
  const names = Object.keys(schemaProperties(contract))
    .filter((name) => schemaBinding(contract, name)?.authority.kind === "supplied")
    .sort((left, right) => left.localeCompare(right, "en-US"));
  const sections = names.map((name) => `## ${schemaNativeMarkdownFieldHeading(name)}`);
  return `<!-- ${ARTIFACT_CONTRACT_TEMPLATE_NOTICE} -->\n\n${sections.join("\n\n")}\n`;
}

/**
 * Native Issue Form top-level keys (`title`/`labels`/`assignees`) can only carry a
 * fixed, deterministic value baked in at generation time: they have no supported
 * mechanism for `supplied` end-user input, `platform` values, or `derived`
 * computation. Anything else with a governed presence fails closed instead of
 * silently disappearing from the projection.
 */
const ISSUE_FORM_TOP_LEVEL_PROPERTIES: ReadonlySet<string> = new Set(["title", "labels", "assignees"]);

function issueFormPropertyProjection(contract: ArtifactContract): {
  readonly topLevel: Readonly<Record<string, unknown>>;
  readonly violations: readonly NativeTemplateProjectionViolation[];
} {
  const violations: NativeTemplateProjectionViolation[] = [];
  const topLevel: Record<string, unknown> = {};
  for (const [name, declaration] of Object.entries(contract.properties)) {
    if (!activeProperty(declaration)) continue;
    const path = `$.properties.${name}`;
    if (!ISSUE_FORM_TOP_LEVEL_PROPERTIES.has(name)) {
      addUnsupported(
        violations,
        path,
        `Native Issue Form has no supported projection for governed property "${name}".`,
      );
      continue;
    }
    if (declaration.authority.kind !== "fixed") {
      addUnsupported(
        violations,
        `${path}.authority`,
        `Native Issue Form top-level "${name}" can only project a fixed value; "${declaration.authority.kind}" authority has no supported representation.`,
      );
      continue;
    }
    topLevel[name] = Array.isArray(declaration.authority.value)
      ? [...declaration.authority.value]
      : declaration.authority.value;
  }
  return { topLevel, violations };
}

/**
 * The native `PULL_REQUEST_TEMPLATE.md` target is Markdown body content only:
 * GitHub does not interpret any front matter or metadata block from it. Every
 * governed pull-request property therefore has no native representation, and
 * any presence other than `unused` must fail closed rather than be dropped.
 */
function pullRequestPropertyViolations(contract: ArtifactContract): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  for (const [name, declaration] of Object.entries(contract.properties)) {
    if (!activeProperty(declaration)) continue;
    addUnsupported(
      violations,
      `$.properties.${name}`,
      `Native pull-request Markdown template has no supported projection for governed property "${name}".`,
    );
  }
  return violations;
}

function issueFieldElement(field: ActiveField): Record<string, unknown> {
  if (field.primitive === "text") {
    return {
      type: "textarea",
      id: field.id,
      attributes: { label: field.id },
      ...(requiredField(field) ? { validations: { required: true } } : {}),
    };
  }
  if (field.primitive === "choice") {
    const values = field.constraints?.values ?? [];
    return {
      type: "dropdown",
      id: field.id,
      attributes: { label: field.id, options: values, multiple: true },
      ...(requiredField(field) ? { validations: { required: true } } : {}),
    };
  }
  const items = field.constraints?.items ?? [];
  return {
    type: "checkboxes",
    id: field.id,
    attributes: {
      label: field.id,
      options: items.map((item) => ({ label: item.label, ...(item.required ? { required: true } : {}) })),
    },
    ...(requiredField(field) ? { validations: { required: true } } : {}),
  };
}

function validateIssueFields(contract: ArtifactContract): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  for (const [index, field] of (contract.fields ?? []).entries()) {
    if (field.primitive === "attachment")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Attachment fields have no supported native Issue Form projection.",
      );
    if (field.primitive === "choice" && activeField(field)) {
      const minItems = field.constraints?.minItems ?? 0;
      const maxItems = field.constraints?.maxItems;
      const values = field.constraints?.values ?? [];
      if (values.some((value) => value !== value.trim() || value.includes(",")))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.values`,
          "Native Issue Form multi-select options cannot contain commas or surrounding whitespace.",
        );
      if (maxItems !== undefined)
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.maxItems`,
          "Native Issue Form multi-select cannot enforce a maximum selection count.",
        );
      if (minItems > 1 || (minItems > 0 && !requiredField(field)))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.minItems`,
          "Native Issue Form can enforce only the required/non-required selection boundary.",
        );
    }
    if (field.primitive === "checklist" && activeField(field)) {
      const labels = (field.constraints?.items ?? []).map((item) => item.label);
      if (new Set(labels).size !== labels.length || labels.some((label) => label !== label.trim()))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native Issue Form checklist labels must be unique and trimmed.",
        );
    }
  }
  return violations;
}

function validatePullRequestFields(contract: ArtifactContract): readonly NativeTemplateProjectionViolation[] {
  const violations: NativeTemplateProjectionViolation[] = [];
  for (const [index, field] of (contract.fields ?? []).entries()) {
    if (field.primitive === "choice")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Choice fields have no native pull-request-template field representation.",
      );
    if (field.primitive === "attachment")
      addUnsupported(
        violations,
        `$.fields[${index}].primitive`,
        "Attachment fields have no native pull-request-template field representation.",
      );
    if (field.primitive === "checklist" && activeField(field)) {
      const items = field.constraints?.items ?? [];
      if (items.some((item) => item.required))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native pull-request Markdown cannot encode required checklist items.",
        );
      const labels = items.map((item) => item.label);
      if (new Set(labels).size !== labels.length || labels.some((label) => label !== label.trim()))
        addUnsupported(
          violations,
          `$.fields[${index}].constraints.items`,
          "Native pull-request Markdown checklist labels must be unique and trimmed.",
        );
    }
  }
  return violations;
}

function issueDocument(
  contract: ArtifactContract,
  topLevelProperties: Readonly<Record<string, unknown>>,
): Readonly<Record<string, unknown>> {
  const fields = (contract.fields ?? []).filter(suppliedField);
  return {
    name: contract.id,
    description: `Artifact Contract ${contract.id}`,
    ...topLevelProperties,
    body: fields.map((field) => issueFieldElement(field)),
  };
}

function renderIssueDocument(document: Readonly<Record<string, unknown>>): string {
  return `# ${ARTIFACT_CONTRACT_TEMPLATE_NOTICE}\n${stringifyYaml(document, { lineWidth: 0 })}`;
}

function markdownField(field: ActiveField): string {
  const heading = `## ${field.id}`;
  if (field.primitive === "text") return heading;
  const items = (field.constraints?.items ?? []).map((item) => `- [ ] ${item.label}`).join("\n");
  return `${heading}\n\n${items}`;
}

function renderPullRequestDocument(contract: ArtifactContract): string {
  const fields = (contract.fields ?? []).filter(suppliedField);
  return `${fields.map(markdownField).join("\n\n")}\n`;
}

/** Project a v2 Issue Artifact Contract into a native Issue Form. */
export function projectArtifactContractToIssueForm(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativeIssueFormProjection {
  const contract = contractFromInput(input);
  if (contract.kind !== "issue")
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Issue Form projection requires an issue contract.",
      },
    ]);
  if (isSchemaNativeContract(contract)) {
    const supported = assertSchemaNativeIssueFormCapability(contract);
    const document = schemaNativeIssueDocument(supported);
    const supplied = (document.body as readonly unknown[]).length > 0;
    if (!supplied)
      throw new NativeTemplateProjectionError([
        {
          code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
          path: "$.bindings",
          message: "Issue Form projection requires at least one supplied property.",
        },
      ]);
    return {
      kind: "issue_form",
      path: generatedPath(contract, options.path),
      document: document as NativeIssueFormProjection["document"],
      content: renderIssueDocument(document),
    };
  }
  const { topLevel, violations: propertyViolations } = issueFormPropertyProjection(contract);
  const violations = [...validateIssueFields(contract), ...propertyViolations];
  const supplied = (contract.fields ?? []).some(suppliedField);
  if (!supplied)
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.fields",
      message: "Issue Form projection requires at least one supplied body field.",
    });
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  const document = issueDocument(contract, topLevel);
  return {
    kind: "issue_form",
    path: generatedPath(contract, options.path),
    document: document as NativeIssueFormProjection["document"],
    content: renderIssueDocument(document),
  };
}

/** Project a v2 Pull Request Artifact Contract into a native Markdown template. */
export function projectArtifactContractToPullRequestTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativePullRequestTemplateProjection {
  const contract = contractFromInput(input);
  if (contract.kind !== "pull_request")
    throw new NativeTemplateProjectionError([
      {
        code: "NATIVE_TEMPLATE_PROJECTION_INVALID_CONTRACT",
        path: "$.kind",
        message: "Pull request template projection requires a pull_request contract.",
      },
    ]);
  if (isSchemaNativeContract(contract)) {
    const supported = assertSchemaNativePullRequestMarkdownCapability(contract);
    return {
      kind: "pull_request_template",
      path: generatedPath(contract, options.path),
      document: {},
      content: renderSchemaNativePullRequestDocument(supported),
    };
  }
  const violations = [...validatePullRequestFields(contract), ...pullRequestPropertyViolations(contract)];
  const supplied = (contract.fields ?? []).some(suppliedField);
  if (!supplied)
    violations.push({
      code: "NATIVE_TEMPLATE_PROJECTION_EMPTY",
      path: "$.fields",
      message: "Pull request template projection requires at least one supplied body field.",
    });
  if (violations.length > 0) throw new NativeTemplateProjectionError(violations);
  return {
    kind: "pull_request_template",
    path: generatedPath(contract, options.path),
    document: {},
    content: `<!-- ${ARTIFACT_CONTRACT_TEMPLATE_NOTICE} -->\n\n${renderPullRequestDocument(contract)}`,
  };
}

/** Project an Artifact Contract to its kind-specific native GitHub template. */
export function projectArtifactContractToNativeTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): NativeTemplateProjectionResult {
  const contract = contractFromInput(input);
  return contract.kind === "issue"
    ? projectArtifactContractToIssueForm(contract, options)
    : contract.kind === "pull_request"
      ? projectArtifactContractToPullRequestTemplate(contract, options)
      : (() => {
          throw new NativeTemplateProjectionError([
            {
              code: "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY",
              path: "$.kind",
              message: "Branch Artifact Contracts do not have a native Issue Form or pull-request-template projection.",
            },
          ]);
        })();
}

export function renderArtifactContractIssueForm(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToIssueForm(input, options).content;
}

export function renderArtifactContractPullRequestTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToPullRequestTemplate(input, options).content;
}

export function renderArtifactContractNativeTemplate(
  input: unknown,
  options: ArtifactContractNativeTemplateProjectionOptions = {},
): string {
  return projectArtifactContractToNativeTemplate(input, options).content;
}

// Naming aliases follow the existing semantic artifact projection surface and
// keep callers from having to encode the target's historical file format.
export const projectIssueArtifactContract = projectArtifactContractToIssueForm;
export const projectPullRequestArtifactContract = projectArtifactContractToPullRequestTemplate;
export const projectArtifactContractToNative = projectArtifactContractToNativeTemplate;
export const renderArtifactContractToIssueForm = renderArtifactContractIssueForm;
export const renderArtifactContractToPullRequestTemplate = renderArtifactContractPullRequestTemplate;

/** Stable path helper shared by local template sync and callers previewing output. */
export function artifactContractNativeTemplatePath(contract: Pick<ArtifactContract, "kind" | "id">): string {
  return generatedPath(contract, undefined);
}
