import assert from "node:assert/strict";
import { test } from "node:test";
import {
  NativeTemplateProjectionError,
  parseArtifactContract,
  projectArtifactContractToIssueForm,
  projectArtifactContractToPullRequestTemplate,
} from "./index.js";

const issueContract = {
  version: "1",
  kind: "issue",
  id: "feature",
  properties: {},
  fields: [
    { id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } },
    {
      id: "areas",
      primitive: "choice",
      presence: "optional",
      authority: { kind: "supplied" },
      constraints: { values: ["core", "cli"] },
    },
    {
      id: "checks",
      primitive: "checklist",
      presence: "optional",
      authority: { kind: "supplied" },
      constraints: { items: [{ id: "tests", label: "Tests", required: true }] },
    },
  ],
} as const;

test("projects an Issue Artifact Contract directly to a deterministic Issue Form", () => {
  const contract = parseArtifactContract(issueContract);
  const first = projectArtifactContractToIssueForm(contract);
  const second = projectArtifactContractToIssueForm(structuredClone(issueContract));

  assert.equal(first.path, ".github/ISSUE_TEMPLATE/feature.yml");
  assert.equal(first.content, second.content);
  assert.match(first.content, /type: textarea/u);
  assert.match(first.content, /multiple: true/u);
  assert.match(first.content, /required: true/u);
  assert.match(first.content, /label: Tests/u);
});

test("projects supported PR text/checklist fields without treating Markdown as Canon", () => {
  const contract = parseArtifactContract({
    version: "1",
    kind: "pull_request",
    id: "default",
    properties: {},
    fields: [
      { id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } },
      {
        id: "checks",
        primitive: "checklist",
        presence: "optional",
        authority: { kind: "supplied" },
        constraints: { items: [{ id: "tests", label: "Tests", required: false }] },
      },
    ],
  });
  const projection = projectArtifactContractToPullRequestTemplate(contract);
  assert.equal(projection.path, ".github/PULL_REQUEST_TEMPLATE.md");
  assert.match(projection.content, /^<!-- Generated by gh-inari from Artifact Contract; do not edit\. -->/u);
  assert.match(projection.content, /## summary\n\n## checks\n\n- \[ \] Tests/u);
});

test("fails closed for native capabilities that cannot preserve semantic state", () => {
  const attachment = parseArtifactContract({
    version: "1",
    kind: "issue",
    id: "attachment",
    properties: {},
    fields: [
      {
        id: "files",
        primitive: "attachment",
        presence: "required",
        authority: { kind: "supplied" },
        constraints: { minItems: 1 },
      },
    ],
  });
  assert.throws(
    () => projectArtifactContractToIssueForm(attachment),
    (error: unknown) =>
      error instanceof NativeTemplateProjectionError &&
      error.violations.some((violation) => violation.code === "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY"),
  );

  const choice = parseArtifactContract({
    version: "1",
    kind: "pull_request",
    id: "choice",
    properties: {},
    fields: [
      {
        id: "area",
        primitive: "choice",
        presence: "required",
        authority: { kind: "supplied" },
        constraints: { values: ["core"] },
      },
    ],
  });
  assert.throws(() => projectArtifactContractToPullRequestTemplate(choice), NativeTemplateProjectionError);
});

test("projects fixed title/labels/assignees onto the native Issue Form top level", () => {
  const contract = parseArtifactContract({
    version: "1",
    kind: "issue",
    id: "feature",
    properties: {
      title: { presence: "required", authority: { kind: "fixed", value: "feat: " } },
      labels: { presence: "optional", authority: { kind: "fixed", value: ["enhancement"] } },
      assignees: { presence: "optional", authority: { kind: "fixed", value: ["octocat"] } },
    },
    fields: [{ id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } }],
  });
  const projection = projectArtifactContractToIssueForm(contract);
  assert.equal(projection.document.title, "feat: ");
  assert.deepEqual(projection.document.labels, ["enhancement"]);
  assert.deepEqual(projection.document.assignees, ["octocat"]);
  assert.match(projection.content, /title: "feat: "/u);
  assert.match(projection.content, /labels:\s*\n\s*- enhancement/u);
});

test("fails closed when a governed property has no native Issue Form representation", () => {
  const supplied = parseArtifactContract({
    version: "1",
    kind: "issue",
    id: "feature",
    properties: { title: { presence: "required", authority: { kind: "supplied" } } },
    fields: [{ id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } }],
  });
  assert.throws(
    () => projectArtifactContractToIssueForm(supplied),
    (error: unknown) =>
      error instanceof NativeTemplateProjectionError &&
      error.violations.some(
        (violation) =>
          violation.code === "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY" &&
          violation.path === "$.properties.title.authority",
      ),
  );

  const milestone = parseArtifactContract({
    version: "1",
    kind: "issue",
    id: "feature",
    properties: {
      milestone: {
        presence: "optional",
        authority: { kind: "derived", derive: { op: "format", template: "{parent.number}" } },
      },
      parent: { presence: "required", authority: { kind: "supplied" } },
    },
    fields: [{ id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } }],
  });
  assert.throws(
    () => projectArtifactContractToIssueForm(milestone),
    (error: unknown) =>
      error instanceof NativeTemplateProjectionError &&
      error.violations.some((violation) => violation.path === "$.properties.milestone") &&
      error.violations.some((violation) => violation.path === "$.properties.parent"),
  );
});

test("fails closed for any governed pull-request property, since the native template is Markdown-only", () => {
  const contract = parseArtifactContract({
    version: "1",
    kind: "pull_request",
    id: "default",
    properties: { title: { presence: "required", authority: { kind: "fixed", value: "chore: release" } } },
    fields: [{ id: "summary", primitive: "text", presence: "required", authority: { kind: "supplied" } }],
  });
  assert.throws(
    () => projectArtifactContractToPullRequestTemplate(contract),
    (error: unknown) =>
      error instanceof NativeTemplateProjectionError &&
      error.violations.some(
        (violation) =>
          violation.code === "NATIVE_TEMPLATE_PROJECTION_UNSUPPORTED_CAPABILITY" &&
          violation.path === "$.properties.title",
      ),
  );
});
