/**
 * Public managed-runtime composition seam.
 *
 * This module only composes the production Runtime/Session boundaries.  The
 * Session key is generated by `createManagedSession`, the Runtime signs the
 * public-only issuance request through `issueSessionCertificate`, and request
 * proof is delegated to `signSessionRequest`.  Runtime/workspace labels are
 * returned as bounded provenance and never enter the certificate claims.
 */

import type { KeyObject } from "node:crypto";
import {
  createManagedSession,
  issueSessionCertificate,
  type IssuedSessionCertificate,
  type ManagedSession,
  type ManagedSessionIssuanceRequest,
} from "./session-issuance.js";
import { signSessionRequest, type SemanticSessionRequest, type SessionRequestEnvelope } from "./session-request.js";
import type { CapabilityClaim } from "./capability.js";
import type { RuntimeAuthority } from "./runtime-authority.js";
import type { RuntimeAuthorityKeyPair } from "./runtime-key.js";
import type { SessionCertificateRepository, SessionCertificateTask } from "./session-certificate.js";

/** Provenance is diagnostic metadata only; it is not a Session principal. */
export interface ManagedRuntimeProvenance {
  /** Runtime implementation label, not a Runtime Authority identity. */
  readonly runtime?: string;
  /** Optional worktree label, not a repository or authorization identity. */
  readonly worktree?: string;
  /** Optional workspace spelling used by managed-runtime integrations. */
  readonly workspace?: string;
  /** Optional Session label, not the certificate Session subject. */
  readonly session?: string;
}

export const MAX_MANAGED_RUNTIME_PROVENANCE_KEYS = 4 as const;
export const MAX_MANAGED_RUNTIME_PROVENANCE_LABEL_LENGTH = 128 as const;

const MANAGED_RUNTIME_OPTION_KEYS = new Set([
  "repository",
  "task",
  "capabilities",
  "ttlSeconds",
  "runtimeAuthority",
  "runtimeKey",
  "now",
  "provenance",
]);
const MANAGED_RUNTIME_PROVENANCE_KEYS = new Set(["runtime", "worktree", "workspace", "session"]);
const SAFE_PROVENANCE_LABEL = /^[\x20-\x7e]+$/u;
const SENSITIVE_PROVENANCE_LABEL = /(?:private\s*key|secret|token|credential|jwt|installation|begin\s+[-a-z]+\s+key)/iu;

export type ManagedRuntimeSessionErrorCode = "MANAGED_RUNTIME_INVALID_OPTIONS" | "MANAGED_RUNTIME_INVALID_PROVENANCE";

export interface ManagedRuntimeSessionDiagnostic {
  readonly code: ManagedRuntimeSessionErrorCode;
  readonly path: string;
  readonly message: string;
}

/** Stable, bounded, secret-safe validation error for the composition seam. */
export class ManagedRuntimeSessionError extends Error {
  readonly code: ManagedRuntimeSessionErrorCode;
  readonly diagnostics: readonly ManagedRuntimeSessionDiagnostic[];

  constructor(
    code: ManagedRuntimeSessionErrorCode,
    message: string,
    diagnostics: readonly ManagedRuntimeSessionDiagnostic[] = [],
  ) {
    super(message);
    this.name = "ManagedRuntimeSessionError";
    this.code = code;
    this.diagnostics = Object.freeze([...diagnostics]);
  }
}

export interface ManagedRuntimeSessionOptions {
  readonly repository: SessionCertificateRepository;
  readonly task?: SessionCertificateTask;
  readonly capabilities: readonly CapabilityClaim[];
  readonly ttlSeconds: number;
  /** Trusted Runtime Authority record used by the existing issuance primitive. */
  readonly runtimeAuthority: RuntimeAuthority;
  /** Trusted Runtime-side signing key; it is never retained in the result. */
  readonly runtimeKey: KeyObject | RuntimeAuthorityKeyPair;
  readonly now?: Date;
  readonly provenance?: ManagedRuntimeProvenance;
}

export interface ManagedRuntimeSessionRequestOptions {
  readonly request: SemanticSessionRequest;
  readonly operation: string;
  readonly requestId: string;
  readonly issuedAt: number;
  readonly expiresAt: number;
}

/**
 * Agent-facing result of the managed-runtime composition.
 *
 * It contains the public-only issuance request, the canonical Runtime-signed
 * certificate, and the Session signing seam.  It intentionally has no
 * Runtime key, App credential, or serialized Session private key.
 */
export interface ManagedRuntimeSession {
  readonly session: ManagedSession;
  readonly issuanceRequest: ManagedSessionIssuanceRequest;
  readonly certificate: IssuedSessionCertificate;
  readonly provenance?: ManagedRuntimeProvenance;
  /** Sign the existing canonical Session request envelope. */
  readonly signRequest: (options: ManagedRuntimeSessionRequestOptions) => SessionRequestEnvelope;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function diagnostic(
  code: ManagedRuntimeSessionErrorCode,
  path: string,
  message: string,
): ManagedRuntimeSessionDiagnostic {
  return { code, path, message };
}

function fail(code: ManagedRuntimeSessionErrorCode, message: string, path: string): never {
  throw new ManagedRuntimeSessionError(code, message, [diagnostic(code, path, message)]);
}

function rejectUnknownProperties(
  input: Record<string, unknown>,
  allowed: ReadonlySet<string>,
  code: ManagedRuntimeSessionErrorCode,
  path: string,
): void {
  for (const key of Object.keys(input).sort()) {
    if (!allowed.has(key)) {
      fail(code, "Managed-runtime input contains an unsupported property.", `${path}.${key}`);
    }
  }
}

function validateProvenance(input: unknown): ManagedRuntimeProvenance | undefined {
  if (input === undefined) return undefined;
  if (!isRecord(input)) {
    fail("MANAGED_RUNTIME_INVALID_PROVENANCE", "Managed-runtime provenance must be an object.", "$.provenance");
  }
  rejectUnknownProperties(input, MANAGED_RUNTIME_PROVENANCE_KEYS, "MANAGED_RUNTIME_INVALID_PROVENANCE", "$.provenance");
  const entries = Object.entries(input);
  if (entries.length === 0 || entries.length > MAX_MANAGED_RUNTIME_PROVENANCE_KEYS) {
    fail(
      "MANAGED_RUNTIME_INVALID_PROVENANCE",
      `Managed-runtime provenance must contain 1-${MAX_MANAGED_RUNTIME_PROVENANCE_KEYS} properties.`,
      "$.provenance",
    );
  }
  const normalized: Record<string, string> = {};
  for (const [key, value] of entries) {
    if (
      typeof value !== "string" ||
      value.length === 0 ||
      value.length > MAX_MANAGED_RUNTIME_PROVENANCE_LABEL_LENGTH ||
      !SAFE_PROVENANCE_LABEL.test(value) ||
      SENSITIVE_PROVENANCE_LABEL.test(value)
    ) {
      fail(
        "MANAGED_RUNTIME_INVALID_PROVENANCE",
        `Provenance labels must be printable text of at most ${MAX_MANAGED_RUNTIME_PROVENANCE_LABEL_LENGTH} characters and must not contain credential material.`,
        `$.provenance.${key}`,
      );
    }
    normalized[key] = value;
  }
  return Object.freeze(normalized) as ManagedRuntimeProvenance;
}

function validateOptions(input: unknown): ManagedRuntimeSessionOptions {
  if (!isRecord(input)) {
    fail("MANAGED_RUNTIME_INVALID_OPTIONS", "Managed-runtime options must be an object.", "$");
  }
  rejectUnknownProperties(input, MANAGED_RUNTIME_OPTION_KEYS, "MANAGED_RUNTIME_INVALID_OPTIONS", "$");
  for (const key of ["repository", "capabilities", "ttlSeconds", "runtimeAuthority", "runtimeKey"] as const) {
    if (!(key in input)) {
      fail("MANAGED_RUNTIME_INVALID_OPTIONS", "Managed-runtime option is required.", `$.${key}`);
    }
  }
  const provenance = validateProvenance(input.provenance);
  return {
    repository: input.repository as SessionCertificateRepository,
    ...(input.task === undefined ? {} : { task: input.task as SessionCertificateTask }),
    capabilities: input.capabilities as readonly CapabilityClaim[],
    ttlSeconds: input.ttlSeconds as number,
    runtimeAuthority: input.runtimeAuthority as RuntimeAuthority,
    runtimeKey: input.runtimeKey as KeyObject | RuntimeAuthorityKeyPair,
    ...(input.now === undefined ? {} : { now: input.now as Date }),
    ...(provenance === undefined ? {} : { provenance }),
  };
}

/**
 * Create one managed Session, issue its existing canonical certificate, and
 * return the transport-neutral Session/App integration seam.
 *
 * The Runtime-side key is consumed only by `issueSessionCertificate`; the
 * returned value has no reference to it.  The issuance request sent to that
 * primitive contains the Session public key and existing certificate claims
 * only.
 */
export function createManagedRuntimeSession(options: ManagedRuntimeSessionOptions): ManagedRuntimeSession {
  const normalized = validateOptions(options);
  const session = createManagedSession();
  const issuanceRequest = session.createIssuanceRequest({
    repository: normalized.repository,
    ...(normalized.task === undefined ? {} : { task: normalized.task }),
    capabilities: normalized.capabilities,
    ttlSeconds: normalized.ttlSeconds,
  });
  const certificate = issueSessionCertificate({
    repository: normalized.repository,
    runtimeAuthority: normalized.runtimeAuthority,
    runtimeKey: normalized.runtimeKey,
    request: issuanceRequest,
    ...(normalized.now === undefined ? {} : { now: normalized.now }),
  });
  session.acceptCertificate(certificate);

  const signRequest = (requestOptions: ManagedRuntimeSessionRequestOptions): SessionRequestEnvelope =>
    signSessionRequest({
      session,
      certificate,
      request: requestOptions.request,
      operation: requestOptions.operation,
      requestId: requestOptions.requestId,
      issuedAt: requestOptions.issuedAt,
      expiresAt: requestOptions.expiresAt,
    });

  return Object.freeze({
    session,
    issuanceRequest,
    certificate,
    ...(normalized.provenance === undefined ? {} : { provenance: normalized.provenance }),
    signRequest,
  });
}
