import { readFile as readFileAsync } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import {
  assertCanonicalContract,
  CANONICAL_IR_VERSION,
  CONTRACT_SCHEMA_VERSION,
  type CanonicalContract,
  type CanonicalSection,
  type ChecklistField,
  type ChecklistItem,
  type StringField,
} from "./contract/ir.js";
import { parseMarkdownStructure, type MarkdownHeading, type MarkdownStructure } from "./markdown-ast.js";
import {
  discoverTemplates,
  discoverTemplatesSync,
  selectPullRequestTemplate,
  type TemplateIdentity as DiscoveredTemplateIdentity,
  type TemplateSelector,
} from "./template-discovery.js";

const GENERATED_SEMANTIC_NOTICE = "<!-- Generated by gh-inari from .github/inari; do not edit. -->";

export type PullRequestTemplateErrorCode =
  | "PR_TEMPLATE_EMPTY"
  | "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT"
  | "PR_TEMPLATE_AMBIGUOUS_STRUCTURE"
  | "PR_TEMPLATE_NOT_PULL_REQUEST"
  | "PR_TEMPLATE_READ_FAILED";

export interface PullRequestTemplateErrorDetails {
  readonly path?: string;
  readonly line?: number;
  readonly construct?: string;
  readonly reason?: string;
}

/** A typed failure raised when the supported PR-template subset cannot be represented safely. */
export class PullRequestTemplateError extends Error {
  readonly code: PullRequestTemplateErrorCode;
  readonly details: PullRequestTemplateErrorDetails;

  constructor(
    code: PullRequestTemplateErrorCode,
    message: string,
    details: PullRequestTemplateErrorDetails = {},
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = "PullRequestTemplateError";
    this.code = code;
    this.details = details;
  }

  toJSON(): {
    code: PullRequestTemplateErrorCode;
    message: string;
    details: PullRequestTemplateErrorDetails;
  } {
    return { code: this.code, message: this.message, details: this.details };
  }
}

interface TaskItemSource {
  readonly line: number;
  readonly sourceIndex: number;
  readonly checked: boolean;
  readonly label: string;
}

interface ChecklistBody {
  readonly items: readonly TaskItemSource[];
  readonly placeholder?: string;
  readonly trailingContent?: string;
}

/**
 * Parse one repository-native PR template into the existing canonical IR.
 *
 * The identity is deliberately the discovery-layer identity. This keeps
 * filesystem discovery and parsing as separate concerns while ensuring the
 * compiled contract cannot be detached from a native template path.
 *
 * Markdown grammar, source positions, headings, lists, task-list state and
 * fenced/HTML block boundaries are recognized exclusively through the
 * shared {@link parseMarkdownStructure} CommonMark/GFM adapter. This module
 * owns only the supported PR-template subset admitted on top of that
 * structure and CanonicalContract construction.
 */
export function parsePullRequestTemplate(markdown: string, identity: DiscoveredTemplateIdentity): CanonicalContract {
  assertPullRequestIdentity(identity);
  if (typeof markdown !== "string") {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
      "Pull request template content must be a string.",
      { reason: "non-string template content" },
    );
  }

  const normalized = normalizeSource(markdown);
  const lines = normalized.split("\n");
  const structure = parseMarkdownStructure(normalized);

  assertCommentsTerminated(structure);
  assertNoBlockquotedTasks(structure);
  assertNoHeadingLikeIndentedCode(structure, lines);
  assertSupportedHeadings(structure.headings);

  const headings = structure.headings;
  const sections: CanonicalSection[] = [];
  const usedIds = new Set<string>();

  if (headings.length === 0) {
    const content = trimBlankLines(lines.join("\n"));
    if (content === undefined) {
      throw new PullRequestTemplateError("PR_TEMPLATE_EMPTY", "Pull request template contains no renderable content.");
    }
    if (structure.listItems.some((item) => item.checked !== undefined)) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        "A top-level checklist requires a heading section in the supported PR-template representation.",
        { construct: "top-level checklist" },
      );
    }
    sections.push(createDocumentationSection(content, 0, usedIds));
  } else {
    const preambleEnd = (headings[0]?.startLine ?? 1) - 1;
    const preamble = trimBlankLines(lines.slice(0, preambleEnd).join("\n"));
    if (preamble !== undefined)
      sections.push(createDocumentationSection(preamble, sections.length, usedIds, "preamble_content"));

    headings.forEach((heading, headingIndex) => {
      const nextHeading = headings[headingIndex + 1];
      const bodyStartLine = heading.endLine + 1;
      const bodyEndLine = nextHeading !== undefined ? nextHeading.startLine - 1 : lines.length;
      sections.push(
        ...createInputSections(heading, bodyStartLine, bodyEndLine, lines, structure, sections.length, usedIds),
      );
    });
  }

  const contract: CanonicalContract = {
    irVersion: CANONICAL_IR_VERSION,
    schemaVersion: CONTRACT_SCHEMA_VERSION,
    artifactKind: "pull_request",
    templateIdentity: {
      id: toCanonicalIdentifier(identity.id, "template"),
      name: identity.name,
      path: identity.path,
      source: "pull_request_template",
    },
    nativeMetadata: {
      source: "pull_request_template",
      path: identity.path,
    },
    sections,
    supplementalConstraints: { fields: [] },
  };

  assertCanonicalContract(contract);
  return contract;
}

/** Compile one discovered native PR template from a repository root. */
export async function compilePullRequestTemplate(
  repositoryRoot: string | URL = process.cwd(),
  selector?: string | TemplateSelector,
): Promise<CanonicalContract> {
  const discovery = await discoverTemplates(repositoryRoot);
  const identity = selectPullRequestTemplate(discovery, selector);
  return parsePullRequestTemplate(await readTemplate(discovery.repositoryRoot, identity), identity);
}

/** Synchronous counterpart for callers that already operate synchronously. */
export function compilePullRequestTemplateSync(
  repositoryRoot: string | URL = process.cwd(),
  selector?: string | TemplateSelector,
): CanonicalContract {
  const discovery = discoverTemplatesSync(repositoryRoot);
  const identity = selectPullRequestTemplate(discovery, selector);
  return parsePullRequestTemplate(readTemplateSync(discovery.repositoryRoot, identity), identity);
}

/** Compile all native PR templates in the discovery layer's stable order. */
export async function compilePullRequestTemplates(
  repositoryRoot: string | URL = process.cwd(),
): Promise<readonly CanonicalContract[]> {
  const discovery = await discoverTemplates(repositoryRoot);
  return Promise.all(
    discovery.pullRequestTemplates.map(async (identity) =>
      parsePullRequestTemplate(await readTemplate(discovery.repositoryRoot, identity), identity),
    ),
  );
}

/** Synchronous counterpart of compilePullRequestTemplates. */
export function compilePullRequestTemplatesSync(
  repositoryRoot: string | URL = process.cwd(),
): readonly CanonicalContract[] {
  const discovery = discoverTemplatesSync(repositoryRoot);
  return discovery.pullRequestTemplates.map((identity) =>
    parsePullRequestTemplate(readTemplateSync(discovery.repositoryRoot, identity), identity),
  );
}

/**
 * Render the structural portion of a validated PR contract as canonical GFM.
 * No placeholder, requirement, or policy is invented when the IR does not
 * contain one.
 */
export function renderPullRequestTemplate(input: unknown): string {
  assertCanonicalContract(input);
  if (input.artifactKind !== "pull_request") {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_NOT_PULL_REQUEST",
      "Only pull request contracts can be rendered as pull request templates.",
    );
  }

  const blocks = input.sections.map(renderSection).filter((block) => block.length > 0);
  if (blocks.length === 0) {
    throw new PullRequestTemplateError("PR_TEMPLATE_EMPTY", "Pull request contract contains no renderable sections.");
  }
  return `${blocks.join("\n\n")}\n`;
}

/** Reject unterminated HTML comments; mdast treats them as valid blocks extending to end of input. */
function assertCommentsTerminated(structure: MarkdownStructure): void {
  for (const block of structure.opaqueBlocks) {
    if (block.kind !== "html") continue;
    const text = structure.sourceSlice(block);
    if (text.startsWith("<!--") && !text.includes("-->")) {
      throw new PullRequestTemplateError("PR_TEMPLATE_UNSUPPORTED_CONSTRUCT", "HTML comment is not closed.", {
        line: block.startLine,
        construct: "unclosed HTML comment",
      });
    }
  }
}

function assertNoBlockquotedTasks(structure: MarkdownStructure): void {
  const item = structure.listItems.find((candidate) => candidate.checked !== undefined && candidate.blockquoted);
  if (item !== undefined) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
      "Checklist items inside blockquotes are not representable in the canonical PR section model.",
      { line: item.startLine, construct: "blockquote checklist" },
    );
  }
}

/** A 4+-space indented ATX-like line becomes an indented code block; its ambiguous list/block context is still rejected. */
function assertNoHeadingLikeIndentedCode(structure: MarkdownStructure, lines: readonly string[]): void {
  for (const block of structure.opaqueBlocks) {
    if (block.kind !== "indented-code") continue;
    const text = lines[block.startLine - 1] ?? "";
    if (/^[ \t]+#{1,6}(?:[ \t]+|$)/u.test(text)) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        "Indented headings are not supported because their list/block context is ambiguous.",
        { line: block.startLine, construct: "indented heading" },
      );
    }
  }
}

function assertSupportedHeadings(headings: readonly MarkdownHeading[]): void {
  for (const heading of headings) {
    if (heading.indented) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        "Indented headings are not supported because their list/block context is ambiguous.",
        { line: heading.startLine, construct: "indented heading" },
      );
    }
    if (heading.title.length === 0) {
      throw new PullRequestTemplateError("PR_TEMPLATE_UNSUPPORTED_CONSTRUCT", "Headings must contain a title.", {
        line: heading.startLine,
        construct: "empty heading",
      });
    }
  }
}

function createDocumentationSection(
  content: string,
  order: number,
  usedIds: Set<string>,
  base = "content",
): CanonicalSection {
  const id = uniqueOrThrow(toCanonicalIdentifier(base, "content"), usedIds, undefined, "literal content section");
  return {
    id,
    kind: "documentation",
    content,
    render: { order },
    nativeMetadata: { elementType: "markdown", sourceId: id, markdown: content },
    fields: [],
  };
}

function createInputSections(
  heading: MarkdownHeading,
  bodyStartLine: number,
  bodyEndLine: number,
  lines: readonly string[],
  structure: MarkdownStructure,
  order: number,
  usedIds: Set<string>,
): readonly CanonicalSection[] {
  const id = uniqueOrThrow(
    toCanonicalIdentifier(heading.title, "section"),
    usedIds,
    heading.startLine,
    "heading section",
  );
  const checklist = parseChecklistBody(bodyStartLine, bodyEndLine, lines, structure);
  const field =
    checklist === undefined
      ? createStringField(id, heading.title, bodyStartLine, bodyEndLine, lines)
      : createChecklistField(id, heading.title, checklist);

  const sections: CanonicalSection[] = [
    {
      id,
      title: heading.title,
      kind: "input",
      render: { order, headingLevel: heading.depth },
      nativeMetadata: { elementType: "heading", sourceId: id, headingLevel: heading.depth },
      fields: [field],
    },
  ];
  if (checklist?.trailingContent !== undefined) {
    sections.push(createDocumentationSection(checklist.trailingContent, order + 1, usedIds, `content_after_${id}`));
  }
  return sections;
}

function createStringField(
  id: string,
  label: string,
  bodyStartLine: number,
  bodyEndLine: number,
  lines: readonly string[],
): StringField {
  const placeholder =
    bodyEndLine < bodyStartLine ? undefined : trimBlankLines(lines.slice(bodyStartLine - 1, bodyEndLine).join("\n"));
  return {
    id,
    label,
    type: "string",
    required: "unknown",
    render: { order: 0 },
    nativeMetadata: {
      elementType: "pr_section",
      sourceId: id,
      ...(placeholder === undefined ? {} : { placeholder }),
    },
  };
}

function createChecklistField(id: string, label: string, body: ChecklistBody): ChecklistField {
  const items: ChecklistItem[] = [];
  const itemIds = new Set<string>();
  const checked: string[] = [];

  body.items.forEach((item, index) => {
    const itemId = toCanonicalIdentifier(item.label, "item", index + 1);
    if (itemIds.has(itemId)) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_AMBIGUOUS_STRUCTURE",
        `Checklist item labels produce duplicate structural identity "${itemId}".`,
        { line: item.line, construct: "checklist item identity" },
      );
    }
    itemIds.add(itemId);
    items.push({ id: itemId, label: item.label, required: false });
    if (item.checked) checked.push(itemId);
  });

  const defaultValue = checked.length === 0 ? undefined : checked;
  return {
    id,
    label,
    type: "checklist",
    required: "unknown",
    items,
    render: { order: 0 },
    nativeMetadata: {
      elementType: "pr_section",
      sourceId: id,
      ...(body.placeholder === undefined ? {} : { placeholder: body.placeholder }),
      ...(defaultValue === undefined ? {} : { defaultValue }),
      options: items.map((item) => ({ value: item.id })),
    },
    ...(defaultValue === undefined ? {} : { defaultValue }),
  };
}

/**
 * Detect and structurally validate one heading section's checklist, using
 * GFM task-list items recognized by the shared Markdown structure adapter.
 * Preserves the pre-migration admission rule: a checklist is only
 * representable as one contiguous block of top-level, non-blockquoted task
 * items; anything else interleaved between the first and last task is
 * ambiguous.
 */
function parseChecklistBody(
  bodyStartLine: number,
  bodyEndLine: number,
  lines: readonly string[],
  structure: MarkdownStructure,
): ChecklistBody | undefined {
  if (bodyEndLine < bodyStartLine) return undefined;

  const taskByLine = new Map<number, { readonly checked: boolean; readonly label: string }>();
  for (const item of structure.listItems) {
    if (item.startLine < bodyStartLine || item.startLine > bodyEndLine) continue;
    if (item.checked === undefined) continue;
    if (item.depth > 0) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        "Nested task lists are not representable in the canonical PR section model.",
        { line: item.startLine, construct: "nested checklist" },
      );
    }
    taskByLine.set(item.startLine, { checked: item.checked, label: item.label });
  }
  if (taskByLine.size === 0) return undefined;

  const protectedLines = new Set<number>();
  for (const block of structure.opaqueBlocks) {
    const start = Math.max(block.startLine, bodyStartLine);
    const end = Math.min(block.endLine, bodyEndLine);
    for (let line = start; line <= end; line += 1) protectedLines.add(line);
  }

  const taskLines = [...taskByLine.keys()].sort((left, right) => left - right);
  const firstLine = taskLines[0];
  const lastLine = taskLines[taskLines.length - 1];
  if (firstLine === undefined || lastLine === undefined) return undefined;

  for (let line = firstLine + 1; line < lastLine; line += 1) {
    if (taskByLine.has(line) || protectedLines.has(line)) continue;
    const text = lines[line - 1] ?? "";
    if (text.trim().length === 0) continue;
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_AMBIGUOUS_STRUCTURE",
      "Checklist items must form one contiguous structural block.",
      { line, construct: "checklist block" },
    );
  }

  const items: TaskItemSource[] = taskLines.map((line, index) => {
    const task = taskByLine.get(line);
    const label = task?.label ?? "";
    if (label.length === 0) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        "Checklist items must contain a non-empty label.",
        { line, construct: "empty checklist item" },
      );
    }
    return { line, sourceIndex: index, checked: task?.checked ?? false, label };
  });

  const placeholder = trimBlankLines(lines.slice(bodyStartLine - 1, firstLine - 1).join("\n"));
  const trailingContent = trimBlankLines(lines.slice(lastLine, bodyEndLine).join("\n"));
  return {
    items,
    ...(placeholder === undefined ? {} : { placeholder }),
    ...(trailingContent === undefined ? {} : { trailingContent }),
  };
}

function normalizeSource(markdown: string): string {
  return markdown
    .replace(/^﻿/u, "")
    .replace(new RegExp(`^${GENERATED_SEMANTIC_NOTICE}\\n?`, "u"), "")
    .replace(/\r\n?/gu, "\n");
}

function trimBlankLines(value: string): string | undefined {
  const lines = value.split("\n");
  while (lines[0] !== undefined && lines[0].trim().length === 0) lines.shift();
  while (lines.at(-1) !== undefined && lines.at(-1)?.trim().length === 0) lines.pop();
  if (lines.length === 0) return undefined;
  const result = lines.join("\n");
  return result.length === 0 ? undefined : result;
}

function uniqueOrThrow(base: string, usedIds: Set<string>, line: number | undefined, construct: string): string {
  if (usedIds.has(base)) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_AMBIGUOUS_STRUCTURE",
      `Structural identity "${base}" is not unique in the template.`,
      { line, construct },
    );
  }
  usedIds.add(base);
  return base;
}

function toCanonicalIdentifier(value: string, prefix: string, fallbackIndex?: number): string {
  let identifier = "";
  for (const character of value.normalize("NFKC")) {
    if (/^[A-Za-z0-9_-]$/u.test(character)) {
      identifier += character.toLocaleLowerCase("en-US");
    } else if (/^[\u0000-\u007F]$/u.test(character)) {
      if (!identifier.endsWith("_")) identifier += "_";
    } else {
      const codePoint = character.codePointAt(0);
      identifier += `_${(codePoint ?? 0).toString(16)}_`;
    }
  }
  identifier = identifier.replace(/^_+|_+$/gu, "");
  if (identifier.length === 0) identifier = `${prefix}_${fallbackIndex ?? 1}`;
  if (!/^[A-Za-z]/u.test(identifier)) identifier = `${prefix}_${identifier}`;
  return identifier;
}

function assertPullRequestIdentity(identity: DiscoveredTemplateIdentity): void {
  if (identity.kind !== "pull-request") {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_NOT_PULL_REQUEST",
      "Only repository-native pull request template identities can be compiled.",
      { path: identity.path, reason: "identity kind is not pull-request" },
    );
  }
}

async function readTemplate(repositoryRoot: string, identity: DiscoveredTemplateIdentity): Promise<string> {
  try {
    return await readFileAsync(path.join(repositoryRoot, identity.path), "utf8");
  } catch (error) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_READ_FAILED",
      `Cannot read pull request template ${identity.path}.`,
      { path: identity.path, reason: "filesystem read failed" },
      { cause: error },
    );
  }
}

function readTemplateSync(repositoryRoot: string, identity: DiscoveredTemplateIdentity): string {
  try {
    return readFileSync(path.join(repositoryRoot, identity.path), "utf8");
  } catch (error) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_READ_FAILED",
      `Cannot read pull request template ${identity.path}.`,
      { path: identity.path, reason: "filesystem read failed" },
      { cause: error },
    );
  }
}

function renderSection(section: CanonicalSection): string {
  if (section.kind === "documentation") {
    const content = trimBlankLines(section.content ?? "");
    if (content === undefined) return "";
    if (section.title === undefined) return content;
    const level = section.render.headingLevel ?? section.nativeMetadata.headingLevel;
    if (level === undefined) {
      throw new PullRequestTemplateError(
        "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
        `Documentation section "${section.id}" has a title but no heading level.`,
        { construct: "documentation heading" },
      );
    }
    return [`${"#".repeat(level)} ${section.title}`, content].join("\n\n");
  }

  if (section.title === undefined) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
      `Input section "${section.id}" has no heading title.`,
      { construct: "input section heading" },
    );
  }
  const level = section.render.headingLevel ?? section.nativeMetadata.headingLevel;
  if (level === undefined) {
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
      `Input section "${section.id}" has no heading level.`,
      { construct: "input section heading" },
    );
  }

  const blocks = [`${"#".repeat(level)} ${section.title}`];
  section.fields.forEach((field) => {
    if (field.type === "string" || field.type === "enum" || field.type === "array") {
      appendOptionalBlock(blocks, field.nativeMetadata.placeholder);
      return;
    }
    if (field.type === "checklist") {
      appendOptionalBlock(blocks, field.nativeMetadata.placeholder);
      const checked = new Set(field.defaultValue ?? []);
      blocks.push(field.items.map((item) => `- [${checked.has(item.id) ? "x" : " "}] ${item.label}`).join("\n"));
      return;
    }
    throw new PullRequestTemplateError(
      "PR_TEMPLATE_UNSUPPORTED_CONSTRUCT",
      "This field cannot be rendered by the PR-template compiler.",
      { construct: "non-structural PR field" },
    );
  });
  return blocks.join("\n\n");
}

function appendOptionalBlock(blocks: string[], value: string | undefined): void {
  const block = value === undefined ? undefined : trimBlankLines(value);
  if (block !== undefined) blocks.push(block);
}
