import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import {
  compileSemanticTemplate,
  discoverSemanticTemplates,
  importNativeTemplate,
  normalizeSemanticTemplate,
  parseSemanticTemplate,
  renderSemanticCompactSchema,
  renderSemanticNative,
  SemanticTemplateError,
  syncSemanticTemplates,
} from "./semantic-template.js";

async function withRepository(run: (root: string) => Promise<void>): Promise<void> {
  const root = await mkdtemp(path.join(os.tmpdir(), "gh-inari-semantic-"));
  try {
    await run(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test("semantic Issue source compiles to the canonical IR and a deterministic native form", async () => {
  await withRepository(async (root) => {
    await mkdir(path.join(root, ".github/inari/issues"), { recursive: true });
    const source = {
      version: 1,
      kind: "issue",
      id: "bug",
      name: "Bug",
      description: "Reproducible defect",
      sections: [
        { id: "summary", type: "textarea", label: "Summary", required: true },
        {
          id: "severity",
          type: "enum",
          label: "Severity",
          options: [
            { id: "high", label: "High" },
            { id: "low", label: "Low" },
          ],
        },
        {
          id: "checks",
          type: "checklist",
          label: "Checks",
          options: [{ id: "repro", label: "Reproduced", required: true }],
        },
      ],
    };
    await writeFile(path.join(root, ".github/inari/issues/bug.json"), `${JSON.stringify(source)}\n`);
    const [identity] = await discoverSemanticTemplates(root);
    assert.ok(identity);
    const document = {
      ...identity,
      source: parseSemanticTemplate(JSON.stringify(source)),
    };
    const contract = await compileSemanticTemplate(root, document);
    assert.equal(contract.artifactKind, "issue");
    assert.deepEqual(
      contract.sections.flatMap((section) => section.fields).map((field) => field.id),
      ["summary", "severity", "checks"],
    );
    assert.equal(contract.sections[2]?.fields[0]?.type, "checklist");
    const native = renderSemanticNative(document.source, identity.generatedPath);
    assert.match(native, /^# Generated by gh-inari from \.github\/inari; do not edit\./u);
    assert.equal(native, renderSemanticNative(document.source, identity.generatedPath));
  });
});

test("sync writes projections, --check detects drift, and unchanged generation is byte-stable", async () => {
  await withRepository(async (root) => {
    await mkdir(path.join(root, ".github/inari/issues"), { recursive: true });
    await writeFile(
      path.join(root, ".github/inari/issues/feature.json"),
      `${JSON.stringify({
        version: 1,
        kind: "issue",
        id: "feature",
        name: "Feature",
        description: "Enhancement",
        sections: [{ id: "proposal", type: "textarea", label: "Proposal" }],
      })}\n`,
    );
    const first = await syncSemanticTemplates(root);
    assert.deepEqual(first.written, [".github/ISSUE_TEMPLATE/feature.yml"]);
    const generated = await readFile(path.join(root, ".github/ISSUE_TEMPLATE/feature.yml"), "utf8");
    assert.equal((await syncSemanticTemplates(root)).changed, false);
    await writeFile(path.join(root, ".github/ISSUE_TEMPLATE/feature.yml"), `${generated}# drift\n`);
    const check = await syncSemanticTemplates(root, true);
    assert.deepEqual(check.drift, [".github/ISSUE_TEMPLATE/feature.yml"]);
    assert.equal(check.written.length, 0);
    assert.match(await readFile(path.join(root, ".github/ISSUE_TEMPLATE/feature.yml"), "utf8"), /# drift\n/u);
  });
});

test("PR semantic source preserves fixed documentation, placeholders, and checklist fields", async () => {
  const source = normalizeSemanticTemplate({
    version: 1,
    kind: "pull_request",
    id: "default",
    name: "Default",
    sections: [
      { id: "summary", type: "string", label: "Summary", placeholder: "<!-- describe -->", headingLevel: 2 },
      { id: "checks", type: "checklist", label: "Checks", options: [{ id: "tests", label: "Tests" }], headingLevel: 2 },
      { id: "trailing", kind: "documentation", content: "Fixed documentation." },
    ],
  });
  const native = renderSemanticNative(source, ".github/PULL_REQUEST_TEMPLATE.md");
  assert.match(native, /## Summary\n\n<!-- describe -->/u);
  assert.match(native, /- \[ \] Tests/u);
  assert.match(native, /Fixed documentation\./u);
  const contract = await compileSemanticTemplate(".", {
    id: source.id,
    kind: source.kind,
    name: source.name,
    sourcePath: ".github/inari/pull-request.json",
    generatedPath: ".github/PULL_REQUEST_TEMPLATE.md",
    source,
  });
  const compact = renderSemanticCompactSchema(contract) as {
    fields: Record<string, unknown>;
    required: readonly string[];
  };
  assert.equal((compact.fields.summary as { label: string }).label, "Summary");
  assert.deepEqual(compact.required, []);
});

test("native import creates semantic JSON and rejects unsupported semantic source", async () => {
  await withRepository(async (root) => {
    await mkdir(path.join(root, ".github/ISSUE_TEMPLATE"), { recursive: true });
    await writeFile(
      path.join(root, ".github/ISSUE_TEMPLATE/legacy.yml"),
      [
        "name: Legacy",
        "description: Existing form",
        "body:",
        "  - type: textarea",
        "    id: summary",
        "    attributes:",
        "      label: Summary",
        "    validations:",
        "      required: true",
        "",
      ].join("\n"),
    );
    const imported = await importNativeTemplate(root, ".github/ISSUE_TEMPLATE/legacy.yml");
    assert.equal(imported.path, ".github/inari/issues/legacy.json");
    const serialized = JSON.parse(await readFile(path.join(root, imported.path), "utf8")) as {
      sections: readonly { id: string }[];
    };
    assert.equal(serialized.sections[0]?.id, "summary");
  });

  assert.throws(
    () =>
      parseSemanticTemplate(
        JSON.stringify({
          version: 1,
          kind: "issue",
          id: "x",
          name: "X",
          description: "x",
          sections: [{ id: "x", type: "unsupported", label: "X" }],
        }),
      ),
    (error: unknown) => error instanceof SemanticTemplateError && error.code === "SEMANTIC_TEMPLATE_UNSUPPORTED_FIELD",
  );
});
